CREATE DATABASE IF NOT EXISTS test;

CREATE TABLE IF NOT EXISTS test.usertable (
    YCSB_KEY VARCHAR(255) PRIMARY KEY NOT NULL,
    YCSB_VALUE JSONB NOT NULL
);

TRUNCATE TABLE test.usertable;

GRANT ALL PRIVILEGES ON DATABASE test to postgres;
